### ISSUE TITLE
Adjustable Table Prefix

### ISSUE THREAD

**Issue by befedi** [dregad/dokuwiki-plugin-authwordpress#1]
Hi,
one security advice for securing Wordpress installations is changing the table prefix "wp_" to some random value. At the moment this plugin is not supporting custom table prefix values.

Would it be possible to implement an additional Field for the table prefix?

Kind regards,
Ben

**Comment by dregad** [comment]
Can you kindly test the above change and let me know if this satisfies the requirement ?

**Comment by befedi** [comment]
I've just checked the db of my Wordpress installation. The meta value also changes with a different prefix. So "wp_capabilites" will be different.  But it is still not working if I change the prefix manually.

**Comment by dregad** [comment]
> The meta value also changes with a different prefix. So "wp_capabilites" will be different. 

Sorry, I should have tested that - I just tried the updated plugin on my existing setup.

>  But it is still not working if I change the prefix manually.

I'm not sure exactly what you changed here.

Anyway, I fixed the prefix on capabilities issue, please see Pull request #1 / [config-prefix branch](https://github.com/dregad/dokuwiki-plugin-authwordpress/tree/config-prefix) for details / testing.

**Comment by befedi** [comment]
Hi,
if you have successfully tested it, then I have noch idea what the problem could bei in my case. I updated every file again, checked the configuration, tried it with different users but every time I get the "Sorry, username or password was wrong." message. Is there an easy way to setup debug information in dokuwiki? So that I can check where the problem is. 

Where exactly should the "error_connect_failed" message appear if the connection would not work?

**Comment by dregad** [comment]
The _error_connect_failed_ message is shown then the plugin is not able to connect to the DB at all, and it looks like this 

![2016-01-19 13_59_46-start dokuwiki](https://cloud.githubusercontent.com/assets/449891/12419253/18d5958a-beb5-11e5-94a8-fda3106e4ca5.png)

If you just get the _username or password was wrong_ message, then the given credentials were incorrect, or there is a problem with the SQL statement.

If you have enabled debug mode in, you can add `dbg()` calls in the code to output messages to the screen (see https://www.dokuwiki.org/devel:debugging for more info). I suggest you try to print the SQL query (in function `getUserData()`), and try to execute that on your Wordpress DB manually.

> I updated every file again

Are you sure you got the latest code from the pull request ?

**Comment by befedi** [comment]
Hi Damien,
as I was pretty sure that my credentials were right I tried to check everything else. Extension Manager, Configuration etc. There I found the mistake. Your Plugin was not selected to be the active authentication method. As I was not working with DokuWiki before I was not familiar with the settings.

Now I can log in with my Wordpress Credentials but two more questions is left.
1. How can I make a Wordpress user to an admin account? If this is possible.
2. Is it possible to use the regular accounts and the Wordpress accounts at the same time?

**Comment by dregad** [comment]
> Your Plugin was not selected to be the active authentication

I guess you owe me a :beer: for the time I spent trying to figure out what was wrong with my code :wink: 

> How can I make a Wordpress user to an admin account? If this is possible.

You need to add `@administrator` to the _superuser_ list in DokuWiki config. I updated the [documentation](https://www.dokuwiki.org/plugin:authwordpress#configuration_and_settings) to reflect that.

> Is it possible to use the regular accounts and the Wordpress accounts at the same time?

Not natively with my plugin. You can try to use the [chained authentication plugin](https://www.dokuwiki.org/plugin:authchained) which is supposed to enable that functionality, but I never tried it myself.

**Comment by befedi** [comment]
Thank you so much for the help. :) Now we can start setting it up in our project.
