### ISSUE TITLE
User reset password

### ISSUE THREAD

**Issue by wargamesqcf** [dregad/dokuwiki-plugin-authwordpress#10]
one of my user reset their wordpress password and now they can't log into the wiki with the new password.

**Comment by dregad** [comment]
Sorry, but I am not able to reproduce the problem. I just tried and can login successfully into wiki after resetting the user's password.

**Comment by razzius** [comment]
I ran into an issue where my password worked on Wordpress and didn't work with this plugin. The password had a backslash `\` and less than `<` symbol, which might not have made it through an html sanitizer. Replacing those characters allowed me to log in to both systems.

**Comment by dregad** [comment]
Duplicate of #23, fixed in 2025-01-05
