### ISSUE TITLE
Doesn't seem to be compatible with 2017-02-19a "Frusterick Manners"

### ISSUE THREAD

**Issue by jkester1986** [dregad/dokuwiki-plugin-authwordpress#11]
Plugin seems to be working great with 2016-06-26b "Elenor of Tsort", but when we tried to upgrade to 2017-02-19a "Frusterick Manners", we were no longer able to log in (got an error 500 page)

**Comment by dregad** [comment]
@jkester1986 I'm using the plugin every day without issues on release 2017-02-19b, so I don't think it is the root cause of your problem. I suggest you have a look at the PHP error logs to find out what is causing the HTTP 500 error.

**Comment by jkester1986** [comment]
I followed <a href="https://www.dokuwiki.org/tips:logging#appendix_a">these directions</a> to get logging set up, and nothing is logging to my file. Is there another place the php error logs would be stored without me having to set anything up, in the likely chance I just did setup wrong?

**Comment by dregad** [comment]
> I followed these directions to get logging set up,

I'm not sure this is what you really want, looks more like an audit trail than an error log.

> Is there another place the php error logs would be stored

That really depends on your system. Look for `error_log` value in phpinfo() for the location; if not set it means error are saved in your web server's log (e.g. /var/log/apache2/error.log on Ubuntu). You can try to set it to a file of your choice with `ini_set("error_log", "/tmp/php_errors.log");`
