### ISSUE TITLE
When I switch over to using the authwordpress the current admin account is getting disabled or in accessible.

### ISSUE THREAD

**Issue by whichy** [dregad/dokuwiki-plugin-authwordpress#16]
I am pretty sure i have followed all the instructions. 

It is loosely working - the Wordpress accounts are working to let people login. But they don't appear to be getting their roles. Which means we don't end up with any accounts with Administration rights.

And despite having the box checked the existing admin login isn't working either. So we end up with no administrator.

I've switched it back and forth a few times and am not quite sure what isn't going right  - its so close but not working. 

NEVER MIND - Fixed it.

**Comment by dregad** [comment]
For the benefit of other readers, you probably omitted [Configuration and settings step 3](https://www.dokuwiki.org/plugin:authwordpress#configuration_and_settings):

> Add @administrator to the Superuser list1).
:warning: failure to do so may leave you without any users having admin rights, requiring you to manually edit the configuration file to fix the problem.
