### ISSUE TITLE
Compatibility with MySQL 8.0.2+

### ISSUE THREAD

**Issue by Aetf** [dregad/dokuwiki-plugin-authwordpress#17]
`groups` is a [reserved keyword](https://dev.mysql.com/doc/refman/8.0/en/keywords.html) in MySQL 8.0.2+, and the following statement generates an error while logging in:

https://github.com/dregad/dokuwiki-plugin-authwordpress/blob/864f661ce1af9e8d7076507ab26de1be85b28038/auth.php#L50

**Comment by dregad** [comment]
Thanks for reporting the issue and sorry for taking so long to fix it
