### ISSUE TITLE
Logged in as: ??????? ???????? (wpuser)

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [dregad/dokuwiki-plugin-authwordpress#9]
Hello.

If full username in Wordpress stored in non-English (in my case Russian), when in DokuWiki User Manager page field "Real Name" displayed as "???????" and in all pages in the upper right corner displayed as "Logged in as: ??????? (wpuser)". My WP DB in UTF-8.
What to do to solve the problem ?

**Comment by dregad** [comment]
I didn't test with UTF8 data, so I can't answer you at this time. 
I'm quite busy right now, so I'm not sure when I'll be able to look into this, please bear with me.

**Comment by dregad** [comment]
I can reproduce the problem. It's most likely due to the DB connection not properly setup to handle UTF8. If that's indeed the case it should be a quick fix.

**Comment by dregad** [comment]
It was as I thought. 

You can test the fix by [downloading the plugin from the _dev_ branch](https://github.com/dregad/dokuwiki-plugin-authwordpress/archive/dev.zip). I will prepare an official release later.

**Comment by Aleksey-Maksimov** [comment]
Now everything is fine. Thank you.
